services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - type: bind
        source: /media
        target: /media
          #      - type: bind
          #        source: /path/to/media2
          #        target: /media2
          #        read_only: true
          #      - type: bind
          #        source: /path/to/fonts
          #        target: /usr/local/share/fonts/custom
          #        read_only: true
    restart: 'unless-stopped'
